baseURL: /
#languageCode: en-US
#defaultContentLanguage: en

title: Hugo Learn Documentation
theme: hugo-theme-relearn
metaDataFormat: yaml
#defaultContentLanguageInSubdir: true

params:
  editURL: https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/
  description: Documentation for Hugo Learn Theme
  author.name: Ivan McMower
  showVisitedLinks: true
  disableBreadcrumb: false
  disableNextPrev: false
  disableLandingPageButton: true
  disableMermaid: false
  customMermaidURL: https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js
  titleSeparator: "::"
  alwaysopen: false
  themeVariant: zen-dark

outputs:
  home: [ "HTML", "RSS", "SEARCH" ]

markup:
  goldmark:
    renderer:
      unsafe: true  # default is false
